# Site settings
title: Thailand ETCetera
description:
baseurl: "thailandetcetera"
url: "http://akaligo.github.io"
default-image: default.jpg
google-plus: https://plus.google.com/103163741383795666289/

# Gems
gems: ['jekyll-paginate']

# Build settings
markdown: kramdown
permalink: /:title/
encoding: utf-8
paginate: 8
paginate_path: "/blog/page/:num"

# SASS settings
sass:
  sass_dir: _sass
#  style: compressed

# Include these files/directories in your production _site
include: ['_pages']

# Exclude these files from your production _site
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "gulpfile.js", "package.json"]
